all:
  hosts:
    mail.example.com:  ansible_user=asunners
  children:
    webservers:
      hosts:
        foo.example.com: ansible_user=asunners
        bar.example.com:
    dbservers:
      hosts:
        one.example.com:
        two.example.com:
        three.example.com:
