---
- hosts: all
  become: yes
  tasks:
  - name: Update repositories and upgrade packages (apt update > apt upgrade)
    apt:
      update_cache: yes
      upgrade: 'yes'
      cache_valid_time: 86400
